apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gallery
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gallery
  template:
    metadata:
      labels:
        app: api-gallery
    spec:
      containers:
      - name: api-gallery
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        image: api-gallery:latest
        ports:
          - containerPort: 3000
        restart: on-failure

---

apiVersion: v1
kind: Service
metadata:
  name: api-gallery-service
spec:
  type: LoadBalancer
  selector:
    app: api-gallery
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 3000  